# Generated by Django 6.1.1 on 2026-09-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deployment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='server',
        ),
        migrations.AddField(
            model_name='deployment',
            name='ec2_instance_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deployment',
            name='server_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
