# Generated by Django 6.1.1 on 2026-10-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_deployment_server_deployment_ec2_instance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='logs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deployment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
