# Generated by Django 6.1.1 on 2026-10-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deployment_logs_deployment_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('high_cpu', 'High CPU'), ('server_stopped', 'Server Stopped'), ('deployment_failed', 'Deployment Failed'), ('deployment_successful', 'Deployment Successful')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('ec2_instance_id', models.CharField(blank=True, default='', max_length=100)),
                ('server_name', models.CharField(blank=True, default='', max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
